# -*- coding: utf-8 -*-
"""AI_Crop_Recommendation_System.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MUlGw6Ju-kx5C0hM4tzXFCfgF_oOl76J
"""

!pip install shap googletrans==4.0.0-rc1 flwr -q

!pip install shap googletrans==4.0.0-rc1 flwr xgboost -q

import pandas as pd
import numpy as np
import shap
import joblib

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score

from googletrans import Translator

crop_df = pd.read_csv("/content/Crop_recommendation.csv")
area_df = pd.read_csv("/content/Area under different Crops.csv")
horti_df = pd.read_csv("/content/horticulture-Mandal_wise_Crop_Area_Production_and_Yield_data _2022-23.csv")
water_df = pd.read_csv("/content/ground_water_level_2023_July.csv")
market_df = pd.read_csv("/content/Agricultural Marketing.csv")
price_df = pd.read_csv("/content/day_prices_between_01-11-2025_30-11-2025.csv")

import numpy as np

farmer_input = np.array([[
    float(input("Nitrogen (N): ")),
    float(input("Phosphorus (P): ")),
    float(input("Potassium (K): ")),
    float(input("Temperature: ")),
    float(input("Humidity: ")),
    float(input("pH value: ")),
    float(input("Rainfall: "))
]])

import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, VotingClassifier
from xgboost import XGBClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

# 1. Load and Prepare Data
crop_df = pd.read_csv("/content/Crop_recommendation.csv")
X = crop_df.drop("label", axis=1)
y = crop_df["label"]

# Encode labels
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)

# Split for validation (Crucial for Q1 papers to show test accuracy)
X_train, X_test, y_train, y_test = train_test_split(X, y_encoded, test_size=0.2, random_state=42)

# 2. Define Individual Models
rf_model = RandomForestClassifier(n_estimators=150, random_state=42)
gb_model = GradientBoostingClassifier(n_estimators=150, random_state=42)
xgb_model = XGBClassifier(use_label_encoder=False, eval_metric='mlogloss', random_state=42)

# 3. Create Voting Ensemble (Soft Voting for probability weighting)
# Novelty: Combining bagging and boosting techniques
ensemble_model = VotingClassifier(
    estimators=[('rf', rf_model), ('gb', gb_model), ('xgb', xgb_model)],
    voting='soft'
)

# 4. Train
print("⏳ Training Ensemble Model... (This adds methodological rigor)")
ensemble_model.fit(X_train, y_train)

# 5. Validate
preds = ensemble_model.predict(X_test)
acc = accuracy_score(y_test, preds)
print(f"✅ Ensemble Model Accuracy: {acc*100:.2f}%")

# Fit on full data for the final application
ensemble_model.fit(X, y_encoded)

gw_df = pd.read_csv("/content/ground_water_level_2023_July.csv")
gw_df["value"] = pd.to_numeric(gw_df["value"], errors="coerce")
gw_df = gw_df.dropna(subset=["value"])

crop = recommended_crop.strip().lower()

# Data-driven threshold
high_water_threshold = gw_df["value"].quantile(0.6)

if crop in ["rice", "sugarcane"]:
    suitable_areas = gw_df[gw_df["value"] >= high_water_threshold]
else:
    suitable_areas = gw_df[gw_df["value"] < high_water_threshold]

print("\n💧 Suitable Mandals based on Groundwater:")
if suitable_areas.empty:
    print("No suitable mandals found based on groundwater.")
else:
    display(suitable_areas[["district", "mandal", "value"]])

def calculate_eco_economic_score(crop_name, gw_df, area_df, price_df):
    # 1. Normalize Groundwater Data (Higher is better)
    # We use min-max normalization
    gw_crop = gw_df.copy()
    # Ensure 'value' column is numeric before normalization
    gw_crop['value'] = pd.to_numeric(gw_crop['value'], errors='coerce')
    gw_crop = gw_crop.dropna(subset=['value']) # Drop rows where value couldn't be converted
    if gw_crop['value'].max() - gw_crop['value'].min() == 0:
        gw_crop['water_score'] = 0 # Avoid division by zero if all values are the same
    else:
        gw_crop['water_score'] = (gw_crop['value'] - gw_crop['value'].min()) / (gw_crop['value'].max() - gw_crop['value'].min())

    # 2. Get Yield/Area Data for this crop
    crop_col = crop_name.strip().lower()
    # Check if crop_col exists, if not, create it and fill with 0
    if crop_col not in area_df.columns:
        area_df[crop_col] = 0

    area_crop = area_df[['districts', crop_col]].copy()
    # Convert the crop column to numeric, coercing errors to NaN and then filling NaN with 0
    area_crop[crop_col] = pd.to_numeric(area_crop[crop_col], errors='coerce').fillna(0)

    # Normalize Area (Proxy for suitability/yield potential)
    max_area = area_crop[crop_col].max()
    if max_area == 0: max_area = 1 # Avoid division by zero
    area_crop['area_score'] = area_crop[crop_col] / max_area

    # 3. Merge Water and Area Data
    # Note: gw_df has 'district', area_df has 'districts'. We merge on district.
    merged_df = pd.merge(gw_crop, area_crop, left_on='district', right_on='districts', how='inner')

    # 4. Calculate Composite Index
    # Weights: 50% Water Sustainability, 50% Historic Suitability (Area)
    w1, w2 = 0.5, 0.5
    merged_df['Eco_Score'] = (w1 * merged_df['water_score']) + (w2 * merged_df['area_score'])

    return merged_df.sort_values(by='Eco_Score', ascending=False)

# --- Execution ---
# Get Recommendation
crop_pred = ensemble_model.predict(farmer_input)
recommended_crop = label_encoder.inverse_transform(crop_pred)[0]
print(f"🌱 AI Recommended Crop: {recommended_crop.upper()}")

# Calculate The Novel Index
ranked_locations = calculate_eco_economic_score(recommended_crop, gw_df, area_df, price_df)

print(f"\n🏆 Top 5 Sustainable Locations for {recommended_crop} (Based on Eco-Economic Index):")
display(ranked_locations[['district', 'mandal', 'value', 'Eco_Score']].head(5))

import pandas as pd

area_df = pd.read_csv("/content/Area under different Crops.csv")

# Normalize column names
area_df.columns = area_df.columns.str.strip().str.lower()

print(area_df.columns)

print(area_df.columns.tolist())

# Normalize columns
area_df.columns = area_df.columns.str.strip().str.lower()

crop = recommended_crop.strip().lower()

if crop not in area_df.columns:
    raise Exception(f"❌ Crop '{crop}' not found as a column in Area dataset")

# Get area values for the predicted crop
crop_area_df = area_df[["districts", crop]].copy() # Corrected 'district' to 'districts'

crop_area_df[crop] = pd.to_numeric(crop_area_df[crop], errors="coerce")
crop_area_df = crop_area_df.dropna()

# Best areas = highest area
best_areas = crop_area_df.sort_values(by=crop, ascending=False)

print(f"\n🌾 BEST AREAS TO GROW {recommended_crop.upper()}")
display(best_areas.head(5))

import pandas as pd

price_df = pd.read_csv("/content/day_prices_between_01-11-2025_30-11-2025.csv")

# Normalize column names
price_df.columns = price_df.columns.str.strip().str.lower()
print(price_df.columns)

crop = recommended_crop.strip().lower()

crop_alias = {
    "rice": ["rice", "paddy"],
    "wheat": ["wheat"],
    "maize": ["maize", "corn"],
    "cotton": ["cotton"],
    "sugarcane": ["sugarcane"],
    "groundnut": ["groundnut", "peanut"]
}

valid_crop_names = crop_alias.get(crop, [crop])

price_df["commname"] = price_df["commname"].astype(str).str.lower()

crop_price_df = price_df[price_df["commname"].isin(valid_crop_names)]

if crop_price_df.empty:
    print("⚠️ No price data found for", recommended_crop)
else:
    display(crop_price_df.head())

crop_price_df["model"] = pd.to_numeric(
    crop_price_df["model"], errors="coerce"
)

avg_price = crop_price_df["model"].mean()
max_price = crop_price_df["model"].max()

print(f"\n💰 Expected price for {recommended_crop.upper()}:")
print(f"👉 Average Price : ₹{round(avg_price, 2)} per quintal")
print(f"👉 Best Price    : ₹{round(max_price, 2)} per quintal")

max_model_price = crop_price_df['model'].max()
best_price_markets = crop_price_df[crop_price_df['model'] == max_model_price]

print(f"\n🏆 Markets with Best Price for {recommended_crop.upper()}:")
if not best_price_markets.empty:
    display(best_price_markets[['amcname', 'yardname', 'model']].drop_duplicates().head())
else:
    print("No markets found with the best price.")

explainer = shap.TreeExplainer(global_crop_model)
shap_values_crop = explainer.shap_values(farmer_input)

# Determine the index of the recommended_crop (still needed for explanation text)
recommended_crop_index = np.where(label_encoder.classes_ == recommended_crop)[0][0]

# Correctly extract SHAP values for the recommended crop for the single input sample.
# shap_values_crop is of shape (num_samples, num_features, num_classes) when model_output='raw'
# or (num_classes, num_samples, num_features) when model_output='log_loss'
# However, given the previous error, it was likely (1, num_classes, num_features)
# or directly (num_features, num_classes) for the predicted class.
# The most robust way to get the (num_features,) array for the predicted class:
shap_values_for_crop = shap_values_crop[0][:, recommended_crop_index] if shap_values_crop.ndim == 3 else shap_values_crop[0]
if shap_values_for_crop.ndim > 1:
    shap_values_for_crop = shap_values_for_crop.flatten()

# Create a DataFrame for feature importance
feature_importance_df = pd.DataFrame({
    'feature': X.columns,
    'shap_value': shap_values_for_crop
}).sort_values(by='shap_value', ascending=False)

# Generate SHAP explanation string
shap_explanation = f"### SHAP Explanation for {recommended_crop.upper()}\n"
shap_explanation += "The following features significantly influenced the recommendation:\n\n"

# Top 3 positive contributors
shap_explanation += "**Positive Contributors:**\n"
for index, row in feature_importance_df.head(3).iterrows():
    shap_explanation += f"- {row['feature'].capitalize()}: {row['shap_value']:.2f}\n"

# Top 3 negative contributors
shap_explanation += "\n**Negative Contributors:**\n"
for index, row in feature_importance_df.tail(3).sort_values(by='shap_value', ascending=True).iterrows():
    shap_explanation += f"- {row['feature'].capitalize()}: {row['shap_value']:.2f}\n"


# Construct the full markdown report
full_report_markdown = f"# Crop Recommendation Report\n\n"
full_report_markdown += f"## Recommended Crop: {recommended_crop.upper()}\n\n"

# Add Groundwater suitability section
full_report_markdown += "## Suitable Mandals based on Groundwater\n"
if suitable_areas.empty:
    full_report_markdown += "No suitable mandals found based on groundwater for this crop.\n\n"
else:
    full_report_markdown += suitable_areas[["district", "mandal", "value"]].to_markdown(index=False) + "\n\n"

# Add Best Areas to Grow section
full_report_markdown += f"## Best Areas to Grow {recommended_crop.upper()}\n"
full_report_markdown += best_areas.head(5).to_markdown(index=False) + "\n\n"

# Add Expected Price section
full_report_markdown += f"## Expected Price for {recommended_crop.upper()}\n"
full_report_markdown += f"- Average Price : ₹{round(avg_price, 2)} per quintal\n"
full_report_markdown += f"- Best Price    : ₹{round(max_price, 2)} per quintal\n\n"

# Add Markets with Best Price section
full_report_markdown += f"## Markets with Best Price for {recommended_crop.upper()}\n"
if best_price_markets.empty:
    full_report_markdown += "No markets found with the best price.\n\n"
else:
    full_report_markdown += best_price_markets[['amcname', 'yardname', 'model']].drop_duplicates().head().to_markdown(index=False) + "\n\n"

# Add SHAP Explanation
full_report_markdown += shap_explanation

print(full_report_markdown)

# Note: KernelExplainer is slower but works on Ensembles.
# We use a summary background dataset (kmeans) to speed it up.
import shap
import warnings
warnings.filterwarnings('ignore')

# Summarize background data (using 50 samples)
X_summary = shap.kmeans(X, 50)

# Create Explainer
explainer = shap.KernelExplainer(ensemble_model.predict_proba, X_summary)

# Calculate SHAP values for the specific farmer input
shap_values = explainer.shap_values(farmer_input)

# Visualization
print("\n📊 Feature Contribution Analysis:")

pred_index = crop_pred[0] # This is the index of the predicted class, e.g., 5 for coffee

# Correctly extract SHAP values for the predicted class from the 3D numpy array
# shap_values is typically of shape (n_samples, n_features, n_classes)
shap_values_for_plot = shap_values[0, :, pred_index]

# Safely extract expected_value for the predicted class
expected_value_for_plot = None
if isinstance(explainer.expected_value, np.ndarray) and explainer.expected_value.ndim == 1:
    # If expected_value is a 1D array, check its size
    if len(explainer.expected_value) > pred_index: # If it's multi-class and pred_index is valid
        expected_value_for_plot = explainer.expected_value[pred_index]
    elif len(explainer.expected_value) == 1: # If it's a 1-element array (as indicated by error)
        expected_value_for_plot = explainer.expected_value[0]
elif isinstance(explainer.expected_value, (int, float)): # If it's a scalar
    expected_value_for_plot = explainer.expected_value

if shap_values_for_plot is not None and expected_value_for_plot is not None:
    shap.force_plot(expected_value_for_plot, shap_values_for_plot, farmer_input, feature_names=X.columns, matplotlib=True)
else:
    print("Could not generate SHAP force plot due to unexpected SHAP output format.")

# Ask user for output language
print("\nSelect output language:")
print("en - English")
print("te - Telugu")
print("hi - Hindi")
print("ta - Tamil")

selected_lang = input("Enter language code: ").strip().lower()

from googletrans import Translator

translator = Translator()

def translate_text(text, target_lang):
    if target_lang == "en":
        return text
    translated = translator.translate(text, dest=target_lang)
    return translated.text

def generate_shap_explanation(feature_df, crop):
    explanation = f"\n### Why {crop.upper()} was recommended (Explainable AI)\n\n"
    explanation += (
        "This recommendation is based on how your soil and climate conditions "
        "match the ideal requirements of the crop.\n\n"
    )

    explanation += "**Main reasons supporting this crop:**\n"
    for _, row in feature_df.head(3).iterrows():
        explanation += (
            f"- {row['feature'].capitalize()} value strongly supports {crop} "
            f"(impact score: {row['shap_value']:.2f})\n"
        )

    explanation += "\n**Factors that slightly reduce suitability:**\n"
    for _, row in feature_df.tail(3).sort_values(by="shap_value").iterrows():
        explanation += (
            f"- {row['feature'].capitalize()} has a lower influence "
            f"(impact score: {row['shap_value']:.2f})\n"
        )

    explanation += (
        "\nOverall, the positive factors outweigh the negative ones, "
        f"so {crop.upper()} is recommended as the best crop.\n"
    )

    return explanation

enhanced_shap_explanation = generate_shap_explanation(
    feature_importance_df,
    recommended_crop
)

full_report_markdown += "\n" + enhanced_shap_explanation

from googletrans import Translator
translator = Translator()

def translate_text_safe(text, target_lang):
    if target_lang == "en":
        return text

    try:
        result = translator.translate(text, dest=target_lang)
        if result is None or result.text is None:
            print("⚠️ Translation failed, returning original text")
            return text
        return result.text

    except Exception as e:
        print("⚠️ Translation error:", e)
        return text

def translate_large_text(text, target_lang, chunk_size=3000):
    if target_lang == "en":
        return text

    translated_chunks = []

    for i in range(0, len(text), chunk_size):
        chunk = text[i:i+chunk_size]
        translated_chunk = translate_text_safe(chunk, target_lang)
        translated_chunks.append(translated_chunk)

    return "\n".join(translated_chunks)

translated_report = translate_large_text(full_report_markdown, selected_lang)

print("\n🌍 FINAL REPORT IN SELECTED LANGUAGE:\n")
print(translated_report)